# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitp < Formula
  desc "Pretty git branch exploration for the terminal"
  homepage "https://github.com/sbcinnovation/gitp"
  version "0.8.2"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.2/gitp_0.8.2_darwin_amd64.tar.gz"
      sha256 "9a545b06890389faad2e223a54ba6e16bb056bbba46b729e1d434f2855137b38"

      def install
        bin.install "gitp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.2/gitp_0.8.2_darwin_arm64.tar.gz"
      sha256 "19a0bade38eda1a53f7294a261c97f46475132dc60a7cd5f2dcb05e4c69ba291"

      def install
        bin.install "gitp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.2/gitp_0.8.2_linux_amd64.tar.gz"
      sha256 "848d45d1c0a01242246dbaba556892efbcc5a233fe0b182aba84d3f6e7b29e43"
      def install
        bin.install "gitp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.2/gitp_0.8.2_linux_arm64.tar.gz"
      sha256 "6f4312a0625f7b757569f350b7ee442a5de9bf68ba07f829d2c2a05f47bdfec4"
      def install
        bin.install "gitp"
      end
    end
  end

  test do
    system "#{bin}/gitp", "--version"
  end
end
