# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitp < Formula
  desc "Pretty git branch exploration for the terminal"
  homepage "https://github.com/sbcinnovation/gitp"
  version "0.8.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.1/gitp_0.8.1_darwin_amd64.tar.gz"
      sha256 "9f1c47fc295bdd675f9af93632562021cb6bc0f458c039b9fe54f010300562e2"

      def install
        bin.install "gitp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.1/gitp_0.8.1_darwin_arm64.tar.gz"
      sha256 "422f1eda6a9dd0ab6e18ad931a6e21f7984bf6326c450746adf594479535ed0e"

      def install
        bin.install "gitp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.1/gitp_0.8.1_linux_amd64.tar.gz"
      sha256 "2fc9254f2cebbb24abcc0fac36412a06031f7cf5d632ae33946d08b9451a38c9"
      def install
        bin.install "gitp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/gitp/releases/download/v0.8.1/gitp_0.8.1_linux_arm64.tar.gz"
      sha256 "50c8506fc968a17417e0c75d712f0906c82bc3ebc25a7ce137ca3f3f84d88211"
      def install
        bin.install "gitp"
      end
    end
  end

  test do
    system "#{bin}/gitp", "--version"
  end
end
