# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lmux < Formula
  desc "A fast, simple, cross-platform tmux session manager"
  homepage "https://github.com/sbcinnovation/lmux"
  version "0.8.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.0/lmux_0.8.0_darwin_amd64.tar.gz"
      sha256 "d36b42736a1b62ea513734fdde4e4827529dc64a371ff3639d65eb866c3b3b1b"

      def install
        bin.install "lmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.0/lmux_0.8.0_darwin_arm64.tar.gz"
      sha256 "9d85e98ab9a0c01d88d41c04e5e4e355715d9a94cb7e949d7984826e61be75b8"

      def install
        bin.install "lmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.0/lmux_0.8.0_linux_amd64.tar.gz"
      sha256 "bdb4dbd7d8e1d5359cada371c7d565788c4f080c1072528291c3730d6dc6da11"
      def install
        bin.install "lmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.0/lmux_0.8.0_linux_arm64.tar.gz"
      sha256 "db71a59f83a7ff487d590980e8f003d80a77c2b4630181fc868b6a291095a25c"
      def install
        bin.install "lmux"
      end
    end
  end

  test do
    system "#{bin}/lmux", "version"
  end
end
