# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lmux < Formula
  desc "A fast, simple, cross-platform tmux session manager"
  homepage "https://github.com/sbcinnovation/lmux"
  version "0.8.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.1/lmux_0.8.1_darwin_amd64.tar.gz"
      sha256 "dc4c85a1843b87eb73c368703d3307fd57b0b7abdf4a18c70ae83959e01765bf"

      def install
        bin.install "lmux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.1/lmux_0.8.1_darwin_arm64.tar.gz"
      sha256 "828a1f4a3891df28155af0d68e31717ca01d41ae9eae6f1d6793b55c8168b68a"

      def install
        bin.install "lmux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.1/lmux_0.8.1_linux_amd64.tar.gz"
      sha256 "50d992b0f68aa46dac8dfac11778b4fa584c96f983bce0881b9a45b96694321a"
      def install
        bin.install "lmux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/lmux/releases/download/v0.8.1/lmux_0.8.1_linux_arm64.tar.gz"
      sha256 "eb78f5a7a0694b617a86478042080f7eafee57cbf230b460260544c3ecabc342"
      def install
        bin.install "lmux"
      end
    end
  end

  test do
    system "#{bin}/lmux", "version"
  end
end
