# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squoosh < Formula
  desc "Squoosh CLI – image compression for the terminal"
  homepage "https://github.com/sbcinnovation/sbc-squoosh-cli"
  version "8.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.8/squoosh_8.2.8_darwin_amd64.tar.gz"
      sha256 "3f096d90cc97ea8610546e83d96ab9e3ee774207b24f1dd554b4090ffda60650"

      def install
        bin.install "squoosh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.8/squoosh_8.2.8_darwin_arm64.tar.gz"
      sha256 "07f704dabb5107ae36e82b6698789ab09224c8529c50359ffc4d7b069bf1b692"

      def install
        bin.install "squoosh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.8/squoosh_8.2.8_linux_amd64.tar.gz"
      sha256 "893b7c978af3595f88240152e809fdba942fbee3f22ac846ba8d7bbb6536615a"
      def install
        bin.install "squoosh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.8/squoosh_8.2.8_linux_arm64.tar.gz"
      sha256 "4f6019e5226ffb111cce3210acd344cd89951090b94bcf12960f16fa3272cf51"
      def install
        bin.install "squoosh"
      end
    end
  end

  test do
    system "#{bin}/squoosh", "--version"
  end
end
