# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squoosh < Formula
  desc "Squoosh CLI – image compression for the terminal"
  homepage "https://github.com/sbcinnovation/sbc-squoosh-cli"
  version "8.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.3.0/squoosh_8.3.0_darwin_amd64.tar.gz"
      sha256 "015b3abb61f0881e317efb6caf5ac16381de25facfbac8477af8407add1d7c50"

      def install
        bin.install "squoosh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.3.0/squoosh_8.3.0_darwin_arm64.tar.gz"
      sha256 "53e81abae4ea3c8a47875c0202b8c83002925dfa87b1b89096518eefedc622f4"

      def install
        bin.install "squoosh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.3.0/squoosh_8.3.0_linux_amd64.tar.gz"
      sha256 "64544e72840a90b809592e0ca986affc277b5ebb7937d97bc4f8f0c96502613c"
      def install
        bin.install "squoosh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.3.0/squoosh_8.3.0_linux_arm64.tar.gz"
      sha256 "42c2d6fded2c174ec12ef2fef3c4da90f694cee9a4f884b086c05f8ffee16dd4"
      def install
        bin.install "squoosh"
      end
    end
  end

  test do
    system "#{bin}/squoosh", "--version"
  end
end
