# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squoosh < Formula
  desc "Squoosh CLI – image compression for the terminal"
  homepage "https://github.com/sbcinnovation/sbc-squoosh-cli"
  version "8.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.1/squoosh_8.2.1_darwin_amd64.tar.gz"
      sha256 "4af48021393a71a9d58190178b413af046a9e0d0c1291e7ebe2b3f2bd1fd51ce"

      def install
        bin.install "squoosh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.1/squoosh_8.2.1_darwin_arm64.tar.gz"
      sha256 "f5dd844fb0965b344a3b53e83b4ab7ad45998338914c1ced925371324d895b4a"

      def install
        bin.install "squoosh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.1/squoosh_8.2.1_linux_amd64.tar.gz"
      sha256 "77bf75521036ac5e8de6e9bd54c26d6e9efc4a71b4293e531be0220b627fe0ae"
      def install
        bin.install "squoosh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbcinnovation/squoosh-cli/releases/download/v8.2.1/squoosh_8.2.1_linux_arm64.tar.gz"
      sha256 "f906dc39d705b0e9c1e52c9699541701d611b0e653a38d1eb1ce6d724b07229c"
      def install
        bin.install "squoosh"
      end
    end
  end

  test do
    system "#{bin}/squoosh", "--version"
  end
end
